
.quicknav .page-tab{color:var(--seal-dark);background:#FFF8E8;border-color:rgba(183,45,36,.22)}
.quicknav .page-tab.active{background:var(--seal);color:white;border-color:var(--seal)}
.quicknav .nav-divider{width:1px;flex:0 0 1px;background:var(--line);margin:3px 2px}
.page-hub{max-width:1080px;margin:22px auto 4px;padding:0 24px}.page-hub h2{font-family:'Noto Serif TC',serif;font-size:24px;margin:0 0 5px}.page-hub>p{margin:0 0 13px;color:var(--muted);font-size:13.5px}.page-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.page-card{display:flex;flex-direction:column;min-height:142px;text-decoration:none;background:rgba(255,253,247,.88);border:1px solid rgba(73,45,31,.12);border-radius:15px;padding:14px;box-shadow:0 8px 24px rgba(73,35,22,.06);transition:.18s ease}.page-card:hover{transform:translateY(-2px);box-shadow:var(--shadow)}.page-card i{font-size:23px;color:var(--seal);margin-bottom:8px}.page-card b{font-family:'Noto Serif TC',serif;font-size:17px}.page-card span{font-size:12px;color:var(--muted);margin-top:3px}.page-card.current{border-top:4px solid var(--seal)}.page-card.detailed{border-top:4px solid #7B171A}.page-card.food{border-top:4px solid var(--gold)}.page-card.attractions{border-top:4px solid var(--jade)}.page-card.future{border-style:dashed;opacity:.72;pointer-events:none}.page-card .status{display:inline-block;align-self:flex-start;margin-top:auto;font:600 9.5px 'IBM Plex Mono',monospace;padding:4px 7px;border-radius:999px;background:var(--gold-light);color:#76570d}
.detailed-cta{max-width:1080px;margin:14px auto 5px;padding:15px 20px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:13px;align-items:center;background:linear-gradient(135deg,#FFF8E8,#F4E2BE);border:1px solid rgba(196,154,47,.35);border-left:5px solid var(--seal);border-radius:16px;box-shadow:0 9px 26px rgba(73,35,22,.07)}.detailed-cta>div:first-child{display:grid;place-items:center;width:44px;height:44px;border-radius:50%;background:var(--seal);color:white}.detailed-cta>div:first-child i{font-size:22px}.detailed-cta strong{font-family:'Noto Serif TC',serif;color:var(--seal-dark)}.detailed-cta p{margin:2px 0 0;font-size:12.5px;color:var(--muted)}.detailed-cta>a{display:inline-flex;align-items:center;gap:6px;text-decoration:none;border-radius:999px;background:var(--jade-dark);color:white;padding:9px 12px;font:600 10.5px 'IBM Plex Mono',monospace;white-space:nowrap}
@media(max-width:980px){.page-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:760px){.page-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.page-hub{padding:0 18px}.detailed-cta{margin-left:18px;margin-right:18px;grid-template-columns:auto minmax(0,1fr)}.detailed-cta>a{grid-column:1/-1;justify-self:start}}
@media(max-width:430px){.page-grid{grid-template-columns:1fr}.page-card{min-height:110px}.detailed-cta{margin-left:14px;margin-right:14px}}
